# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message_pb2 as message__pb2


class ModelInferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ModelInferenceRPC = channel.unary_unary(
                '/ModelInferenceService/ModelInferenceRPC',
                request_serializer=message__pb2.InferenceRequest.SerializeToString,
                response_deserializer=message__pb2.InferenceResponse.FromString,
                )


class ModelInferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ModelInferenceRPC(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ModelInferenceRPC': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelInferenceRPC,
                    request_deserializer=message__pb2.InferenceRequest.FromString,
                    response_serializer=message__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModelInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelInferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ModelInferenceRPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModelInferenceService/ModelInferenceRPC',
            message__pb2.InferenceRequest.SerializeToString,
            message__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
