SET(ONNX_SEARCH_PATHS
	/usr/local
	/usr
	/mnt/$ENV{USER}
	${ONNXRUNTIME_PATH}
)

FIND_PATH(ONNX_INCLUDE_DIR onnxruntime_cxx_api.h
	HINTS
	$ENV{ONNXDIR}
	PATH_SUFFIXES onnxruntime/include include
	PATHS ${ONNX_SEARCH_PATHS}
)

FIND_LIBRARY(ONNXMAIN_LIBRARY onnxruntime
    HINTS
    $ENV{ONNXDIR}
    PATH_SUFFIXES onnxruntime/lib lib lib64
    PATHS ${ONNX_SEARCH_PATHS}
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(ONNX REQUIRED_VARS ONNX_LIBRARY ONNX_INCLUDE_DIR)
